name: Deploy To Release

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 指定版本Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      # 安装指定版本pnpm(避免lock文件变更)
      - name: Install pnpm
        run: |
          npm install -g pnpm@9.9.0

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Sync Files To Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: '${{ secrets.FTP_LOCAL_DIR }}'
          server-dir: '${{ secrets.FTP_SERVER_DIR }}'
