### status
GET /status

### register
@username = {{$random.alphabetic()}}
POST /auth/login
content-type: application/json
{
  "email": "{{username}}@gmail.com",
  "password": "123123",
  "code": "PASS",
  "register": true
}

### login
POST /auth/login
content-type: application/json

{
  "email": "iixWSsiQtf@gmail.com",
  "password": "123123",
  "code": "PASS"
}

### code
GET /auth/code?width=200&height=300&type=login
content-type: application/json
