### 检查email已经注册？
# @name check-register
POST /v1/auth/check-register
{
  "email": "nam2222222222222222222222222e@qq.com"
}

### 登录
# @name login
POST /v1/auth/login
{
  "nickname": "iovitz",
  "email": "iovitz@111.com",
  "password": "1a23123",
  "code": "1234"
}

### 注册
# @name register
POST /v1/auth/login
{
  "nickname": "iovitz",
  "email": "iovit2@111.com",
  "password": "1a23123",
  "code": "1234",
  "register": true
}
