name: Deploy Node Server

on:
  push:
    branches:
      - develop
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 部署到预发环境
      - name: Deploy To Pre
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: "${{ secrets.PRE_SERVER_HOST }}"
          username: ${{ secrets.PRE_SERVER_NAME }}
          key: ${{ secrets.PRE_SERVER_SSH_KEY }}
          script: |
            echo 'Set Environment Variable'
            export XIANBING_APP_COOKIE_KEY="${{ secrets.XIANBING_APP_COOKIE_KEY }}"
            export XIANBING_APP_PORT="${{ secrets.XIANBING_APP_PORT }}"
            export XIANBING_DB_MYSQL_DB_NAME="${{ secrets.XIANBING_DB_MYSQL_DB_NAME }}"
            export XIANBING_DB_MYSQL_HOST="${{ secrets.XIANBING_DB_MYSQL_HOST }}"
            export XIANBING_DB_MYSQL_PASSWORD="${{ secrets.XIANBING_DB_MYSQL_PASSWORD }}"
            export XIANBING_DB_MYSQL_PORT="${{ secrets.XIANBING_DB_MYSQL_PORT }}"
            export XIANBING_DB_MYSQL_USER="${{ secrets.XIANBING_DB_MYSQL_USER }}"
            export XIANBING_SECRET_MULTIAVATAR="${{ secrets.XIANBING_SECRET_MULTIAVATAR }}"
            export XIANBING_SECRET_FWALERT="${{ secrets.XIANBING_SECRET_FWALERT}}"

            echo 'Update Code'
            cd ~/apps/xianbing/
            git pull

            echo 'Install Dependence & Build'
            cd server/
            pnpm i
            pnpm build

      - name: Sync Files To Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.APP_H5_FTP_HOST }}
          username: ${{ secrets.APP_H5_FTP_USERNAME }}
          password: ${{ secrets.APP_H5_FTP_PASSWORD }}
          local-dir: "server/dist/"
          server-dir: "~/app/xianbing/"

      # # 部署到预发环境
      # - name: Deploy To Pre
      #   uses: appleboy/ssh-action@v1.1.0
      #   with:
      #     host: "${{ secrets.PRE_SERVER_HOST }}"
      #     username: ${{ secrets.PRE_SERVER_NAME }}
      #     key: ${{ secrets.PRE_SERVER_SSH_KEY }}
      #     script: |
      #       echo 'Set Environment Variable'
      #       export XIANBING_APP_COOKIE_KEY="${{ secrets.XIANBING_APP_COOKIE_KEY }}"
      #       export XIANBING_APP_PORT="${{ secrets.XIANBING_APP_PORT }}"
      #       export XIANBING_DB_MYSQL_DB_NAME="${{ secrets.XIANBING_DB_MYSQL_DB_NAME }}"
      #       export XIANBING_DB_MYSQL_HOST="${{ secrets.XIANBING_DB_MYSQL_HOST }}"
      #       export XIANBING_DB_MYSQL_PASSWORD="${{ secrets.XIANBING_DB_MYSQL_PASSWORD }}"
      #       export XIANBING_DB_MYSQL_PORT="${{ secrets.XIANBING_DB_MYSQL_PORT }}"
      #       export XIANBING_DB_MYSQL_USER="${{ secrets.XIANBING_DB_MYSQL_USER }}"
      #       export XIANBING_SECRET_MULTIAVATAR="${{ secrets.XIANBING_SECRET_MULTIAVATAR }}"

      #       echo 'Update Code'
      #       cd ~/apps/xianbing/
      #       git pull

      #       echo 'Install Dependence & Build'
      #       cd server/
      #       pnpm i
      #       pnpm build

      #       echo 'Reload Server'
      #       pm2 startOrReload --wait-ready ecosystem.config.js
